<?php
session_start();
include("../config.php");
?>
<?php
    if(isset($_SESSION["UID"])){
        unset($_SESSION["UID"]);
        unset($_SESSION["userName"]);
        header("location:../index.php");
}
?>